# Name(s)
**Maxwell Taylor**

**Instructions:** This is an individual assignment, but you may discuss your code with your neighbors.

# Python and NumPy

While other IDEs exist for Python development and for data science related activities, one of the most popular environments is Jupyter Notebooks.

This lab is not intended to teach you everything you will use in this course. Instead, it is designed to give you exposure to some critical components from NumPy that we will rely upon routinely.

## Exercise 0
Please read and reference the following as your progress through this course. 

* [What is the Jupyter Notebook?](https://nbviewer.jupyter.org/github/jupyter/notebook/blob/master/docs/source/examples/Notebook/What%20is%20the%20Jupyter%20Notebook.ipynb#)
* [Notebook Tutorial](https://www.datacamp.com/community/tutorials/tutorial-jupyter-notebook)
* [Notebook Basics](https://nbviewer.jupyter.org/github/jupyter/notebook/blob/master/docs/source/examples/Notebook/Notebook%20Basics.ipynb)

**In the space provided below, what are three things that still remain unclear or need further explanation?**

**YOUR ANSWER HERE**

## Exercises 1-7
For the following exercises please read the Python appendix in the Marsland textbook and answer problems A.1-A.7 in the space provided below.

## Exercise 1

In [1]:
import numpy as np

In [9]:
a = np.array([[2, 2, 2, 2], [2, 2, 2, 2], [2, 2, 2, 2], [2, 2, 2, 2], [2, 2, 2, 2], [2, 2, 2, 2]])
a

array([[2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2]])

In [10]:
a = np.full((6, 4), 2)
a

array([[2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2]])

## Exercise 2

In [11]:
b = np.full((6, 4), 1)
np.fill_diagonal(b, 3)
b

array([[3, 1, 1, 1],
       [1, 3, 1, 1],
       [1, 1, 3, 1],
       [1, 1, 1, 3],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

## Exercise 3

Yes, a * b works cause the dimensions are the same. The dot product doesn't work because the number of columns in a is not equal to the rows in b.

In [12]:
a * b

array([[6, 2, 2, 2],
       [2, 6, 2, 2],
       [2, 2, 6, 2],
       [2, 2, 2, 6],
       [2, 2, 2, 2],
       [2, 2, 2, 2]])

In [13]:
np.dot(a,b)

ValueError: shapes (6,4) and (6,4) not aligned: 4 (dim 1) != 6 (dim 0)

## Exercise 4

The first transposes a to dot along the 6 axis and result in 4 x 4. Second does the opposite.

In [16]:
np.dot(a.transpose(), b)

array([[16, 16, 16, 16],
       [16, 16, 16, 16],
       [16, 16, 16, 16],
       [16, 16, 16, 16]])

In [17]:
np.dot(a, b.transpose())

array([[12, 12, 12, 12,  8,  8],
       [12, 12, 12, 12,  8,  8],
       [12, 12, 12, 12,  8,  8],
       [12, 12, 12, 12,  8,  8],
       [12, 12, 12, 12,  8,  8],
       [12, 12, 12, 12,  8,  8]])

## Exercise 5

In [18]:
def helloWorld():
    display("Hello World") #could also use print

helloWorld()

'Hello World'

## Exercise 6

In [35]:
def outputStats(i, array):
    print("Array " + str(i) + " stats:")
    print("Mean: " + str(np.mean(array)))
    print("Sum: " + str(np.sum(array)))
    print("Median: " + str(np.median(array)))
    print("Max: " + str(np.amax(array)))

def genRandArrays():
    for i in range(4):
        outputStats(i, np.random.randint(10, size=(i+1)))
    
genRandArrays()

Array 0 stats:
Mean: 4.0
Sum: 4
Median: 4.0
Max: 4
Array 1 stats:
Mean: 7.0
Sum: 14
Median: 7.0
Max: 9
Array 2 stats:
Mean: 4.0
Sum: 12
Median: 3.0
Max: 7
Array 3 stats:
Mean: 7.5
Sum: 30
Median: 7.5
Max: 9


## Exercise 7

In [ ]:
# YOUR SOLUTION HERE

## Excercises 8-???
While the Marsland book avoids using another popular package called Pandas, we will use it at times throughout this course. Please read and study [10 minutes to Pandas](https://pandas.pydata.org/pandas-docs/stable/getting_started/10min.html) before proceeding to any of the exercises below.

## Exercise 8
Repeat exercise A.1 from Marsland, but create a Pandas DataFrame instead of a NumPy array.

In [ ]:
# YOUR SOLUTION HERE

## Exercise 9
Repeat exercise A.2 using a DataFrame instead.

In [ ]:
# YOUR SOLUTION HERE

## Exercise 10
Repeat exercise A.3 using DataFrames instead.

In [ ]:
# YOUR SOLUTION HERE

## Exercise 11
Repeat exercise A.7 using a dataframe.

In [ ]:
# YOUR SOLUTION HERE

## Exercises 12-14
Now let's look at a real dataset, and talk about ``.loc``. For this exercise, we will use the popular Titanic dataset from Kaggle. Here is some sample code to read it into a dataframe.

In [ ]:
titanic_df = pd.read_csv(
    "https://raw.githubusercontent.com/dlsun/data-science-book/master/data/titanic.csv"
)
titanic_df

Notice how we have nice headers and mixed datatypes? That is one of the reasons we might use Pandas. Please refresh your memory by looking at the 10 minutes to Pandas again, but then answer the following.

## Exercise 12
How do you select the ``name`` column without using .iloc?

In [ ]:
## YOUR SOLUTION HERE

## Exercise 13
After setting the index to ``sex``, how do you select all passengers that are ``female``? And how many female passengers are there?

In [ ]:
## YOUR SOLUTION HERE
titanic_df.set_index('sex',inplace=True)

## Exercise 14
How do you reset the index?

In [ ]:
## YOUR SOLUTION HERE